= Lambda
:!toc-title:
:!toc-placement:
:toc:

Create serverless applications with Lambda

toc::[]

== About
This module helps you set up your Lambdas with Vy best practices.

== Integrations

This module does also have sub-modules to integrate with different AWS services.

link:modules/sqs_integration[SQS]::
Allow your lambda function to be triggered by SQS queues.

== Usage
To use this module, just add it to your terraform!

[source, hcl]
----
module "lambda" {
  source = "github.com/nsbno/terraform-aws-lambda?ref=x.y.z"

  name = "get-users"

  artifact_type = "s3"
  artifact      = data.vy_artifact_info.this

  runtime = "python3.11"
  handler = "handler.main"

  memory = 256
}
----

== Integration Modules

This module has sub-modules to make integration with other AWS services easier.

link:modules/sqs_integration[SQS]::
This module allows you to trigger your Lambda with SQS queues.

link:modules/api_gw_v2_integration[API Gateway v2]::
This module allows you to trigger your Lambda with API Gateway v2

== Examples

These examples show you how to use this module in different configurations.

link:examples/sqs[SQS]::
This example shows a Lambda that is triggered by an SQS queue.

link:examples/provisioned_concurrency[provisioned_concurrency]::
An example with autoscaling provisioned concurrency.
