= Lambda
:!toc-title:
:!toc-placement:
:toc:

Create serverless applications with Lambda

toc::[]

== Integration Modules

This module has sub-modules to make integration with other AWS services easier.

link:modules/sqs_integration[SQS]::
This module allows you to trigger your Lambda with SQS queues.

link:modules/api_gw_v2_integration[API Gateway v2]::
This module allows you to trigger your Lambda with API Gateway v2


== Usage
Remember to check out the link:variables.tf[*variables*] and link:outputs.tf[*outputs*] to see all options.

IMPORTANT: This module uses lambda aliases. Remember to use the `function_qualifier` instead of using the `function_name` to reference the lambda!

[source, hcl]
----
module "lambda" {
  source = "github.com/nsbno/terraform-aws-lambda?ref=x.y.z"

  name = "get-users"

  artifact_type = "s3"
  artifact      = data.vy_artifact_info.this

  runtime = "python3.11"
  handler = "handler.main"

  memory = 256
}
----


== Examples

These examples show you how to use this module in different configurations.

link:examples/sqs[SQS]::
This example shows a Lambda that is triggered by an SQS queue.

link:examples/provisioned_concurrency[Provisioned Concurrency]::
An example with autoscaling provisioned concurrency.
